//GET
export const REQUEST_ARTICLES_LOAD      = "REQUEST_ARTICLES_LOAD";
export const REQUEST_ARTICLES_SUCCESS   = "REQUEST_ARTICLES_SUCCESS";
export const REQUEST_ARTICLES_ERROR     = "REQUEST_ARTICLES_ERROR";
//GET ONE
export const REQUEST_ARTICLE_LOAD      = "REQUEST_ARTICLE_LOAD";
export const REQUEST_ARTICLE_SUCCESS   = "REQUEST_ARTICLE_SUCCESS";
export const REQUEST_ARTICLE_ERROR     = "REQUEST_ARTICLE_ERROR";
//ADD
export const REQUEST_ADD_ARTICLE_LOAD       = "REQUEST_ADD_ARTICLE_LOAD";
export const REQUEST_ADD_ARTICLE_SUCCESS    = "REQUEST_ADD_ARTICLE_SUCCESS";
export const REQUEST_ADD_ARTICLE_ERROR      = "REQUEST_ADD_ARTICLE_ERROR";
//ADD
export const REQUEST_UPDATE_ARTICLE_LOAD       = "REQUEST_UPDATE_ARTICLE_LOAD";
export const REQUEST_UPDATE_ARTICLE_SUCCESS    = "REQUEST_UPDATE_ARTICLE_SUCCESS";
export const REQUEST_UPDATE_ARTICLE_ERROR      = "REQUEST_UPDATE_ARTICLE_ERROR";
//REMOVE
export const REQUEST_REMOVE_ARTICLE_LOAD = "REQUEST_REMOVE_ARTICLE_LOAD";
export const REQUEST_REMOVE_ARTICLE_SUCCESS = "REQUEST_REMOVE_ARTICLE_SUCCESS";
export const REQUEST_REMOVE_ARTICLE_ERROR = "REQUEST_REMOVE_ARTICLE_ERROR";


